<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Chat conversation threads (one per user). Each thread holds a sequence of
 * chat_messages; the assistant's replies are generated by the Chatbot module's
 * LLM orchestration. See app/Modules/Chatbot.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('chat_threads', function (Blueprint $table): void {
            $table->id();
            $table->foreignId('user_id')->constrained()->cascadeOnDelete();
            $table->string('title', 120)->default('New chat');
            $table->dateTime('last_message_at')->nullable();
            $table->timestamps();

            // Thread list query: a user's threads, newest activity first.
            $table->index(['user_id', 'last_message_at']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('chat_threads');
    }
};
